Yelp/pyramid_swagger

- .travis.yml
- pyramid_swagger/__about__.py
Fixes #76 
Not pretty, but I think the automation is worth it. We can back this out after that issue is resolved properly.
Since 1.3.0 is not covered by this, I deployed it to pypi manually and it now appears at https://pypi.python.org/pypi/pyramid_swagger.
> Address failing pypi deploys

- docs/configuration.rst
- pyramid_swagger/tween.py
- tests/acceptance/response_test.py
- tests/tween_test.py
Currently requests can be excluded by path, or by disabling all path validation.
This PR adds support for excluding some routes from validation as another option before disabling all path validation.
y-m uses a single fallback route for legacy routing, so this will allow us to use path validation for all pyramid views, and exclude legacy views.
> Feature: exclude routes from validation

- pyramid_swagger/__about__.py
See https://www.python.org/dev/peps/pep-0440/#developmental-releases
Bumping us to 1.5.0-dev in anticipation of a 1.5 release. Note the lack of a tag.
> Bump to 1.5.0-dev

- docs/changelog.rst
- docs/conf.py
- docs/external_resources.rst
- docs/glossary.rst
- docs/index.rst
- docs/quickstart.rst
- pyramid_swagger/tween.py
- tests/acceptance/response_test.py
Resolves #79 
Addresses two issues:
* a `Context-Type` was expected even for void responses
* a response of an empty dict would fail validation (because it wasn't None)
> Allow for empty body without headers for void responses

- docs/changelog.rst
- pyramid_swagger/ingest.py
- pyramid_swagger/load_schema.py
- pyramid_swagger/model.py
- pyramid_swagger/tween.py
- tests/acceptance/app/__init__.py
- tests/acceptance/request_test.py
- tests/ingest_test.py
- tests/model_test.py
- tests/sample_schemas/good_app/other_sample.json
- tests/tween_test.py
Resolves #1 - header validation
As I was working on #22 I noticed that I was having to frequently pass around a `resolver`, but that resolver was only ever going to be used with the `schema` that came from the same place.
This refactor exposes a `SchemaValidator` object instead of the the `SchemaAndResolver` object. The validator can be used directly to validate a field from the request or response, but it also stores the original schema which can be used to cast values.
Exposing a validator instead of the schema and resolver should allow us to make changes to the validator (as suggested by some TODOs added in this PR) in a single location (`load_schema`). Previously it would require changes to both `load_schema` and `tween`. 
I think it also makes the tween easier to reason about.  All …
> Expose Validators instead of schemas and resolvers

- .gitignore
- pyramid_swagger/load_schema.py
- pyramid_swagger/tween.py
- tests/acceptance/app/__init__.py
- tests/acceptance/request_test.py
- tests/sample_schemas/good_app/sample.json
- tests/tween_test.py
Adds support for validating arguments of `"paramType": "form"`. Fixes #53. 
Looking for some feedback to make sure I'm doing it right and not missing anything.
> Add support for validating form-encoded bodies

- docs/configuration.rst
- docs/external_resources.rst
- docs/glossary.rst
- docs/index.rst
- docs/quickstart.rst
- pyramid_swagger/__init__.py
- pyramid_swagger/api.py
- pyramid_swagger/ingest.py
- pyramid_swagger/model.py
- pyramid_swagger/tween.py
- tests/acceptance/api_test.py
- tests/acceptance/request_test.py
- tests/acceptance/response20_test.py
- tests/acceptance/response_test.py
- tests/api_test.py
- tests/includeme_test.py
- tests/ingest_test.py
- tests/tween_test.py
Still have some unit tests to write but the core of the functionality is there.
General notes:
- Merged in dnephin's branch from https://github.com/striglia/pyramid_swagger/pull/95
- I used a parameterized pytest fixture in `tests/acceptance/request_test.py` to exercise code paths for the variations of `pyramid_swagger.swagger_versions`. Was not able to do with with `response_test.py` hence `response20_test.py`
- Tested with a pyramid app using swaggerpy as a 1.2 client, and bravado as a 2.0 client
> Service both Swagger 1.2 and 2.0 clients 

- .travis.yml
Builds like [this](https://travis-ci.org/striglia/pyramid_swagger/builds/62315510) were failing as Travis was picking 2.0.0 tox version and throwing encoding errors. Still need to figure out the root cause.
> Pin Tox version to 1.9.2 to prevent Travis picking up 2.0.0

- pyramid_swagger/__init__.py
- pyramid_swagger/api.py
- pyramid_swagger/ingest.py
- pyramid_swagger/model.py
- tests/ingest_test.py
This addresses task 4 in #94 
It starts to add support for a things:
* it will allow multiple sets of api_docs to be registered by calling `pyramid_swagger.api.register_api_doc_endpoints`. This will be necessary for our transition to swagger 2.0. The plan is currently to serve api docs for both swagger 1.2 and 2.0, but only validate against the 2.0 specs.  This way both sets of clients will continue to work.
* allows for the base_path of the api docs to be customized, this is kind of necessary if we're registering multiple sets of docs
* provides a method on the `SwaggerSchema` interface that can be used to abstract away the difference between swagger 1.2 and 2.0 api docs. This will allow us to keep all the version switches in a single module (`pyramid_swagger.ingest`).
I've left the …
> Refactor api_doc registering to support 2.0

- pyramid_swagger/tween.py
- tests/tween_test.py
Before this change, a SwaggerMappingError originating from bravado-core during request validation would surface as HTTP 5XX errors instead of HTTP 4XX.  This PR updates the `validation_error` decorator to transform SwaggerMappingError (it already did this for jsonschema.exceptions.ValidationError).
The same will be done for responses during response validation (see `swaggerize_response`)
> Fix request validation errors to surface as HTTP 4XX instead of HTTP5XX

- docs/changelog.rst
- pyramid_swagger/__about__.py
- setup.py
- tests/sample_schemas/good_app/swagger.json
This will fail in travis until https://github.com/Yelp/bravado-core/pull/21 is merged and bravado-core 1.0.0-rc1 is packaged and released.
> Bump to 2.0.0-rc2

- docs/changelog.rst
- docs/configuration.rst
- docs/migrating_to_swagger_20.rst
- docs/quickstart.rst
- pyramid_swagger/ingest.py
- tests/ingest_test.py
This adds a new config key to pyramid_swagger and passes it on to bravado-core.  When ```use_models``` is set to ```False```, models are not generated from the incoming request. This retains compatibility with existing Swagger 1.2 views where models are represented as dicts.
> Add pyramid_swagger.use_models config key

- docs/changelog.rst
- pyramid_swagger/__about__.py
- pyramid_swagger/tween.py
- tests/tween_test.py
When response validation is enabled, error responses are validated against the normal response type, often producing errors. Instead, we should not validate error responses, as in Swagger 1.2, the types of error messages are not well defined. This fixes #121.
This is a rebase of #122 onto the new swagger_12 branch. GitHub doesn't let you switch the branches involved in a pull request (boo) so here's a new PR.
> Don't attempt to validate error responses

- docs/changelog.rst
- pyramid_swagger/ingest.py
- setup.py
- tests/acceptance/relative_ref_test.py
- tests/ingest_test.py
- tests/sample_schemas/relative_ref/parameters/common.json
- tests/sample_schemas/relative_ref/paths/common.json
- tests/sample_schemas/relative_ref/responses/common.json
- tests/sample_schemas/relative_ref/swagger.json
- Send absolute url to `Spec.from_dict` so that 'relative' `$ref`  get resolved relative to the absolute url of `swagger.json` spec.
- Fixes #131
> Send absolute swagger spec url to bravado-core

- docs/quickstart.rst
Routes aren't currently auto-populated. This is not obvious from the Quickstart documentation, leading to at least one reported issue (#120) and some mis-spent hours. This commit adds some clarifying language to docs/quickstart.rst.
> Quickstart documentation update to eliminate confusion about routes.

- docs/changelog.rst
- docs/configuration.rst
- pyramid_swagger/__init__.py
- pyramid_swagger/ingest.py
- pyramid_swagger/tween.py
- setup.py
- tests/acceptance/format_test.py
- tests/ingest_test.py
- tests/tween_test.py
This results in no changes to the pyramid-swagger public interface.
To see changes since 2.4.0: http://bravado-core.readthedocs.org/en/latest/changelog.html#id1
> Upgrade bravado-core dependency to 3.0.2

- pyramid_swagger/tween.py
- tests/acceptance/app/__init__.py
Pyramid seems to remove the preceding '/' from the route_prefix. This ensures that the '/' exists, and adds a test proving that it's broken/fixed.
> Fix issue with pyramid route_prefix

- tox.ini
This enables people to create their virtualenv in the same folder that 
the project is in, and still enable them to run `tox`. Without it, pytest
attempts to process all the files in your virtualenv.
> Only run tests in the `test/` folder.

- pyramid_swagger/api.py
- setup.py
See https://github.com/Yelp/bravado-core/issues/78 for context.
This updates pyramid_swagger to serve up an ingestible Swagger Spec to clients with x-scope metadata removed.
Tested end to end with internal example_happyhour.
> Require bravado-core 4.2.0 so x-scope metadata is not sent to clients.

- pyramid_swagger/__init__.py
- pyramid_swagger/api.py
- pyramid_swagger/ingest.py
- pyramid_swagger/tween.py
- setup.py
- tests/acceptance/invalid_file_test.py
- tests/acceptance/response20_test.py
- tests/acceptance/response_test.py
- tests/acceptance/yaml_test.py
- tests/ingest_test.py
- tests/sample_schemas/yaml_app/defs.yaml
- tests/sample_schemas/yaml_app/swagger.yaml
This was a bit more straightforward than I expected. After the changes in bravado-core, all I needed to do was reuse the bravado-core url handlers to open the file.
I also added a new configuration directive that allows you to define the file name (allowing you to use `swagger.yaml`). 
Two future ideas:
1.Ccombine `pyramid_swagger.schema_directory` and `pyramid_swagger.schema_file` to a single directive. The two fields seem redundant.
2. There are some issues with support for the `/api-docs/swagger.json` endpoint. It works on its own, but the yaml files that it links to are, well, yaml files, which prevents any swagger UIs from consuming them. I was considering finding a way to recombine the external yaml files into a single json file before returning it, but wanted to get people's …
> Add yaml support

- pyramid_swagger/api.py
- pyramid_swagger/tween.py
- tests/acceptance/api_test.py
- tests/acceptance/relative_ref_test.py
- tests/acceptance/yaml_test.py
- tests/api_test.py
- tests/includeme_test.py
- tests/sample_schemas/recursive_app/external/external.json
- tests/sample_schemas/recursive_app/external/swagger.json
- tests/sample_schemas/recursive_app/internal/swagger.json
- tests/tween_test.py
This adds support for serving up all the external files that make up a swagger schema, and the ability to translate between json and yaml transparently.
In other words, if you have a `swagger.yaml` file that references a `models.json` file, all of the following requests return files:
- `GET /swagger.yaml` (the external reference will be rewritten to `{$ref: models.yaml}` to match the requested format
- `GET /swagger.json` (with the `$ref` rewritten to `models.json`)
- `GET /models.json`
- `GET /models.yaml`
This also inherently solves the recursive schema issue, #160 
This was a little tougher to accomplish than repackaging the entire schema as a single file. The changes can be broken down into three chunks: 
a) creating all the appropriate routes, 
b) serving up all the schemas
c) hiding …
> Serve full schemas, individually

- docs/configuration.rst
- pyramid_swagger/api.py
- tests/acceptance/relative_ref_test.py
- tests/sample_schemas/relative_ref/dereferenced_swagger.json
- tests/sample_schemas/relative_ref/paths/common.json
- tests/sample_schemas/relative_ref/responses/common.json
- tests/sample_schemas/relative_ref/swagger.json
Add an option to serve full swagger schemas with all schema refs
resolved (The behavior prior to pyramid_swagger 2.3.0-rc2).
During a deployment where servers are distributed, there can be a transient period where some servers have an old version of a schema and a new version of a schema.  In pyramid_swagger 2.3.0-rc2, a schema is built from multiple requests from each ref.  If a new schema tries to resolve a ref but points to an old schema (or vice versa) during the transient deploy period, there can be issues in the resulting schema.  This pull request adds an option to use the old behavior prior to 2.3.0-rc2 where the server resolves all the refs and serves the fully dereferenced schema upon a request for swagger.{json, yaml}
> Add serve_dereferenced_swagger_schema parameter

- docs/configuration.rst
- pyramid_swagger/api.py
- tests/acceptance/recursive_app_test.py
- tests/acceptance/relative_ref_test.py
- tests/marshaller_test.py
- tox.ini
With the last release was added the ``dereference_served_schema`` parameter.
As described by the documentation the parameter is not working well in case of recursive model definition.
The PR includes the possibility to generate a single file swagger specs even in case of recursive model definition. It reaches the goal allowing local references only for the [definition objects](http://swagger.io/specification/#definitionsObject).
The generated specs are tested respect to the [bravado](https://github.com/Yelp/bravado) client.
Ping: @striglia, @lucagiovagnoli, @sjaensch
> Allow recursive references in single file specs aggregation.

- tox.ini
Users running tests with Python 2.6 could have problems related to twisted that ends into ``ImportError: Twisted requires Python 2.7 or later.``.
The PR is solving this issue limiting the twisted version to 15.5 in case of Python 2.6.
> Tox file improvement

- tests/acceptance/api_test.py
- tests/acceptance/format_test.py
- tests/acceptance/invalid_file_test.py
- tests/acceptance/prefer_20_routes_test.py
- tests/acceptance/recursive_app_test.py
- tests/acceptance/relative_ref_test.py
- tests/acceptance/request_test.py
- tests/acceptance/response20_test.py
- tests/acceptance/response_test.py
- tests/acceptance/yaml_test.py
- tox.ini
The class FixtureRequest has moved in pytest 3, causing the tests to fail. Also there were warnings since pytest assumed TestApp was a class that contains tests.
> Fix pytest 3 errors and warnings, add version requirement

- docs/changelog.rst
- pyramid_swagger/__about__.py
- setup.cfg
- setup.py
On Python 3, reading files returns unicode strings. If no encoding is specified when opening the file then the system locale is used for decoding file contents. If that locale is ASCII (POSIX) then installation of pyramid_swagger fails since README.rst contains the non-ASCII © character.
This PR also prepares the 2.3.0 release. The release candidates have seen some heavy internal use, I think we're good to go.
> Fix installation issue with Python 3 on systems with POSIX locale

- .travis.yml
- docs/changelog.rst
- pyramid_swagger/tween.py
- tests/acceptance/yaml_test.py
- tests/marshaller_test.py
- tests/tween_test.py
- tox.ini
webob >= 1.7 does not return a content type, while we require one during validation. This makes sure pyramid_swagger as well as our tests run with both an older and a new version of webob. I ran the tests with the latest versions of webob (1.7.1) and pyramid (1.8.2), webob 1.6.3 and pyramid 1.7.1 as well as the latest version of webob and pyramid 1.7.1. pyramid 1.8 requires webob 1.7.
Fixes #185
> Fix error, test failures due to new webob not returning content type

- pyramid_swagger/exceptions.py
- pyramid_swagger/tween.py
- tests/acceptance/request_test.py
We'll only do this if path validation is turned on; otherwise Pyramid itself will return a 404 if no matching route is registered. So not only does the 404 make more sense, it also better fits with what Pyramid does.
During testing I uncovered that the `test_400_if_extra_body_args` uses the wrong URL, that test all of a sudden also started returning a 404. This is because the correct URL is `/sample`, not `/sample_post`.
This partially fixes #2.
> Return a 404 when a path cannot be found in the Swagger spec

- .travis.yml
We're already using the latest `tox` when running tests locally, let's do the same for travis runs.
> Unpin tox version used by travis

- .travis.yml
I should have done this as part of the last PR, but unfortunately I noticed it too late. Python 3.5 seems to become somewhat the "standard" Python 3 version, with a lot of long-term supported distributions shipping it. Let's use it as the version we test against on travis.
> Use Python 3.5 for travis run

- tests/acceptance/app/__init__.py
- tests/acceptance/request_test.py
The test was not testing anything, as the path requested is defined in the swagger spec. We now register a Pyramid route that is not defined in the spec, and have two tests that do the same thing but assert different results depending on the config value.
Fixes #64.
> Fix broken exclude_path acceptance test

- docs/changelog.rst
- docs/configuration.rst
- pyramid_swagger/tween.py
- tests/acceptance/app/config.ini
- tests/acceptance/config_ini_test.py
- tests/tween_test.py
Use the pyramid `asbool` and `aslist`[functions](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/settings.html) when reading config values. This branch now includes tests to confirm that settings are read correctly as well as another fix for reading the supported swagger versions, which is read in a different function.
Fixes #182, #200
> Fix boolean config values if read from ini file

- docs/configuration.rst
We didn't have this one in the configuration.rst page.
> Add docs for schema_file config flag

- pyramid_swagger/api.py
- pyramid_swagger/load_schema.py
- pyramid_swagger/model.py
- pyramid_swagger/tween.py
- tests/acceptance/api_test.py
- tests/model_test.py
use request.path_info for matching api paths, which allows reverse proxying an API on a subpath.
> support virtual hosting

- setup.py
- tests/sample_schemas/relative_ref/dereferenced_swagger.json
This PR is needed to fix tests failure related to a bug introduced by ``bravado-core`` ([Issue #190](https://github.com/Yelp/bravado-core/issues/190)).
The test update is needed because from ``bravado-core >= 4.8.3`` responses can be collected on top level ``responses`` property.
> Fix tests due to bravado core flattening update

- docs/configuration.rst
- pyramid_swagger/ingest.py
- tests/ingest_test.py
In some cases we need to use [JSON Merge Patch Format](https://tools.ietf.org/html/rfc7386) for PATCH resource. If we need to update only person's last name we send `{'last_name': 'Name'}` ignoring other fields but current logic set `None` to all fields that weren't included into request. 
Bravado added special parameter `include_missing_properties` to handle such cases so it would be great to add support of this config property into Your library.
Default value is `True` so I updated test to handle `False` case.
> Adding support of new Bravado param `include_missing_properties`

- docs/changelog.rst
- docs/conf.py
- docs/quickstart.rst
- pyramid_swagger/__init__.py
- pyramid_swagger/renderer.py
- pyramid_swagger/tween.py
- tests/acceptance/app/__init__.py
- tests/acceptance/request_test.py
- tests/ingest_test.py
- tests/renderer_test.py
- tests/sample_schemas/good_app/api_docs.json
- tests/sample_schemas/good_app/echo_date.json
- tests/sample_schemas/good_app/swagger.json
- tox.ini
While working with ``pyramid_swagger`` I noticed that the view responses are never marshaled via ``bravado-core`` methods. This means that if our specs are using ``format`` schema property the ``to_wire`` is never called (more info on [User-Defined Formats](http://bravado-core.readthedocs.io/en/latest/formats.html)).
Let's imagine that we have a view that returns a string with ``date`` format.
With the current (pre PR) pyramid_swagger the developer needs to enforce on the view the correct formatting of the object that represent the date (ie. ``datetime.date.today().isoformat()``), which could be annoying and different from what is happening with the input parameters (``request.swagger_data`` contains un-marshaled data, so the date string in the HTTP request will be converted to …
> pyramid_swagger renderer

- docs/configuration.rst
- pyramid_swagger/ingest.py
- tests/ingest_test.py
Fixes #220.
This PR deprecates (with a warning only for now) the usage of ``pyramid_swagger.xxx`` configs for the configuration of the underlying ``bravado_core`` instance.
In order to _trick_ bravado-core related configs ``bravado_core.xxx`` should be used instead.
> bravado-core passthrough configs

- pyramid_swagger/tween.py
- tests/tween_test.py
See https://github.com/Yelp/bravado-core/pull/216 for context
This commit will be required to use the newest version of bravado-core once that PR is merged
> Fixes #222 - Add "raw_bytes" property to OutgoingResponse usages for msgpack support

- pyramid_swagger/renderer.py
During an investigation over a pyramid-swagger instance serving Swagger 1.2 specs I've noticed that in case `pyramid_swagger_rendered` is used to render a response of a Swagger 1.2 endpoint it fails with `AttributeError` as `operation` attribute is not injected into request object for those type of endpoints.
I've noticed that the issue is caused by the fact that `getattr` is not using a default value to prevent exception to be raised.
NOTE: The renderer was defined keeping in consideration that in case of swagger1.2 endpoints the renderer should react as NOOP (`if not operation: return response_object`)
> Gracefully handle operation attribute not set in request during rendering

- tests/acceptance/yaml_test.py
Due to the latest changes in bravado-core the specs used for testing will have x-model in the swagger file returned by pyramid-swagger.
I'm addressing this by ignoring the presence of x-model in the response.
> Fix tests failure related to x-model presence

- pyramid_swagger/ingest.py
- pyramid_swagger/load_schema.py
- tests/acceptance/api_test.py
- tests/ingest_test.py
The goal of this PR is to reduce the amount of warnings related to pyramid swagger configurations.
#221 added warnings in case of presence of `pyramid_swagger` configuration that are mainly used for configuring `bravado-core`.
The warning mentions that keys like `pyramid_swagger.enable_request_validation` are deprecated, but the codebase does still use them.
This means that users following the warning would replace `pyramid_swagger.enable_request_validation` with `bravado_core.validate_requests` but the tweens needed for the validation are added only if `pyramid_swagger.enable_request_validation` is set.
As pyramid-swagger does still support Swagger1.2, it would be odd to use `bravado_core.validate_requests` as Swagger1.2 does not actually use bravado-core.
> Remove warnings related to deprecated pyramid_swagger configurations

- pyramid_swagger/api.py
- pyramid_swagger/load_schema.py
- setup.py
- tests/acceptance/recursive_app_test.py
- tests/acceptance/relative_ref_test.py
- tests/acceptance/yaml_test.py
- tests/api_test.py
The goal of this PR is to reduce the amount of errors returned by the usage of deprecated functions.
I've addressed the two families of warnings:
1. yaml related -> replaced `yaml.(load|dump)` with `yaml.safe_(load|dump)`
2. jsonschema related -> updated `SchemaValidator.from_schema` logic to use a non deprecated approach to build the validator instance
NOTE: this requires jsonschema>=3
> Reduce usage of deprecated methods

- tests/api_test.py
- tests/ingest_test.py
- tests/model_test.py
- tests/spec_test.py
The goal of this PR is to fix the failing tests.
> Fix exception assertions' content

- docs/quickstart.rst
There is a small typo in docs/quickstart.rst.
Should read `marshalling` rather than `marsharling`.
> docs: Fix simple typo, marsharling -> marshalling

- docs/quickstart.rst
- pyramid_swagger/load_schema.py
There are small typos in:
- docs/quickstart.rst
- pyramid_swagger/load_schema.py
Fixes:
- Should read `initial` rather than `intial`.
- Should read `appropriate` rather than `approriate`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- tests/acceptance/api_test.py
- tests/acceptance/config_ini_test.py
- tests/acceptance/prefer_20_routes_test.py
- tests/acceptance/request_test.py
- tests/acceptance/response_test.py
- tests/includeme_test.py
- tests/ingest_test.py
- tests/model_test.py
- tox.ini
Python 3.5 and older are end of life'd, so let's drop them. I added Python 3.8 and 3.10. If you need 3.9, feel free to add it!
About the Swagger 1.2 tests
1. They fail
2. It's unclear to me how they worked in the past - the `ValidatorMap` enum requires six parameter keys in the loaded schemas - all of the test schemas I checked were missing at least one of these values (some defined none at all)
3. Swagger 1.2 is a really old spec, so we're not too concerned about continuing to have test coverage for it.
4. I decided to skip instead of delete these tests to make it easier to spot check 1.2 functionality if anyone needs to.
> Update tox to py3.8/3.10 and skip all Swagger 1.2-related tests

- docs/changelog.rst
- pyramid_swagger/__about__.py
- pyramid_swagger/tween.py
- tests/acceptance/app/config.ini
- tests/acceptance/config_ini_test.py
- tests/acceptance/response20_test.py
- tests/tween_test.py
We want to add the ability to exclude routes for only response validation (while keep request response)
> Add response_validation_exclude_routes support

- setup.py
Our system does not recognize the license text `BSD 3-clause` in `pyramid_swager.__about__`.
Add BSD license classifier
While `license` is a free-form way to specify the licence in setuptools, classifiers have a standard notation that is machine consumable (https://pypi.org/classifiers/)
> Add license metadata via classifier
